name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag movie_dictionary:$(date +%s)
    
    - name: Logs in to docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Building the Docker Image and sends it to Docker Hub
      uses: docker/build-push-action@v2.9.0
      with:
        push: true
        tags: sumos77/movie_dictionary:$(date +%s)
